openapi: "3.0.0"
info:
  version: 1.0.0
  title: pet-owners-api
  description: This is a sample API for an agency that tracks pets adopted by owners.
paths:
  /owners/{ownerId}:
    get:
      summary: Info for a specific owner
      operationId: showOwnerById
      tags:
        - owners
      parameters:
        - name: ownerId
          in: path
          required: true
          description: The id of the owner to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Owner"

components:
  schemas:
    Owner:
      required:
        - id
        - firstName
        - lastName
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        tag:
          type: string